name:                symbolise
version:             0.0.0.1
github:              "Qqwy/haskell-symbolize"
license:             BSD-3-Clause
author:              "Qqwy / Marten"
maintainer:          "qqwy@gmx.com"
copyright:           "2023-2025 Marten Wijnja"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            You want Symbolize with a Z
category:            Data, Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  You want Symbolize with a Z:

  Hackage: <https://hackage.haskell.org/package/symbolize>

  GitHub: <https://github.com/qqwy/haskell-symbolize>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  dependencies: 
  - base < 0
  - youProbablyWantSymbolizeWithAZ < 0
  source-dirs: src
  language: Haskell2010
